### ISSUE TITLE
Won't Start After Initial Run on Windows 10

### ISSUE THREAD

**Issue by octagonalsquare** [azagaya/laigter#101]
I installed this a few days ago and used it with no problem. Then, the other day, I tried using it again, and it opens a window, the window stays plain white, and then it gives the "not responding" error.

I can force it to close without issue.

I tried reinstalling it and uninstalling and installing again to no avail.

This is with version 1.11.0

**Comment by Calinou** [comment]
Do you have a multi-monitor setup and/or NVIDIA Optimus graphics?

**Comment by octagonalsquare** [comment]
I’ve got a dual monitor setup, yes. I’m running a 2070 Super, but not
Optimus I don’t think.

**Comment by azagaya** [comment]
Do you find the same issue with portable and installer?

**Comment by octagonalsquare** [comment]
> Do you find the same issue with portable and installer?

yes, both fail

**Comment by azagaya** [comment]
I'm not being able to reproduce this in any of the Windows PC i tested on. I suspect is a problem in your system. Have you tried in other computers just to be sure?

In your NVIDIA configuration, can you select Laigter to use the GPU?

**Comment by octagonalsquare** [comment]
I don't have a second computer. But I unplugged one monitor and it worked fine. And it works after plugging it back in, as long as I launch it with the monitor unplugged. Which is a pretty annoying process to have to unplug the monitor every time I need to launch it.

What is causing this?

**Comment by azagaya** [comment]
Im not sure what is causing this. My setup also includes multiple monitors and im not being able to reproduce the issue. As calinou suggested, i believe this may have something to do with your graphics setup, as the gpu is in charge of controlling the multiple monitors.

Are both of your monitors connected to the GPU? or is it one of them to the motherboard?

Do you have your gpu drivers updated to latest?
