### ISSUE TITLE
Can't change normal map after/while previewing

### ISSUE THREAD

**Issue by unlessgames** [azagaya/laigter#107]
This tool is awesome!

Not sure if it's a bug or just how it works, but once I go over to Preview the lights, the normal map can no longer be tweaked.

It would be great if this was possible and even more so if one could tweak the normal map *while* in Preview mode.

https://github.com/user-attachments/assets/b5230496-1f10-4be8-98e7-78bda5bb1202

Tested on Linux

**Comment by azagaya** [comment]
Hey! Is a bit of an UX problem, but you have to select the sprite before changing the sliders.
You can change the normal map settings in any view mode, but the sprite needs to be selected. So after moving the light, click on the sprite, and then modify the normal map.

This is this way for the case when you have multiple sprites in view. Perhaps i could work on something to dont loose the selection when moving the light.

**Comment by unlessgames** [comment]
Thanks! That was it.

Cool, I didn't know it can handle multiple images at once but maybe there could be a special case for when you have only a single image loaded which would always stay selected?

Alternatively, the section for the normal map sliders could go gray when the selection isn't relevant (like if it's a light), similar to how the Light section goes gray if there is no light selected. Because right now, this might be the most confusing part that the sliders are there and you can tweak them but nothing happens, if they were gray it would hint that some selection has to happen first and until then they aren't supposed to be interacted with.

**Comment by azagaya** [comment]
yes, making the section gray is a good idea. Ill do that

**Comment by azagaya** [comment]
fixed here af3f7dda796e63d91ed80962fc11cb8dd3e45936
