### ISSUE TITLE
Feature request: Hot reload images

### ISSUE THREAD

**Issue by unlessgames** [azagaya/laigter#109]
It would be nice to be able to change an image on disk and have the resulting changes propagate to the normal maps and so on inside Laigter automatically.

As a first step towards such a workflow, just having a "reimport image" button somewhere on the interface would be cool.

**Comment by azagaya** [comment]
Mmm this was working in the past, It may be broken... ill check

**Comment by azagaya** [comment]
should be fixed in dd6f703930b504702f660cc61726b7f5111179ca
