### ISSUE TITLE
Remove generated files from Git

### ISSUE THREAD

**Issue by Calinou** [azagaya/laigter#13]
I noticed the repository includes some generated files such as `compile_commands.json` and `*.qm`. We should look at removing them from the repository, and generate them at build-time instead.

**Comment by azagaya** [comment]
That's true. We should add them to the gitignore.

**Comment by azagaya** [comment]
I don't see any other files that should be removed

**Comment by Calinou** [comment]
I think this should be fine for now :slightly_smiling_face:

Just to make sure, does the build system generate `*.qm` files automatically? Otherwise, a manual step would be required to get translations to work.

**Comment by azagaya** [comment]
You are right, qm files were needed. I readded them. Thanks!

**Comment by Calinou** [comment]
@azagaya The point was to generate them using QMake, to avoid bloating the repository with binary files that change with every translation update. See https://wiki.qt.io/Automating_generation_of_qm_files.

**Comment by azagaya** [comment]
Ah, ok. I'm reopening this!

**Comment by azagaya** [comment]
Now i think it works fine.

**Comment by azagaya** [comment]
Now i think it works fine.
