### ISSUE TITLE
The Discord link in CONTRIBUTING.md is invalid

### ISSUE THREAD

**Issue by Calinou** [azagaya/laigter#15]
There's a link to a Discord server in [CONTRIBUTING.md](https://github.com/azagaya/laigter/blob/master/CONTRIBUTING.md), but it says "Invite Invalid" when I try to join it. Is anyone else able to reproduce this?

**Comment by azagaya** [comment]
I'm sorry, i forgot to put the option to never expire.
https://discord.gg/88kJqry
