### ISSUE TITLE
textures do not stay at their relative positions when resizing

### ISSUE THREAD

**Issue by Lodugh** [azagaya/laigter#23]
Just a small Issue I noticed, when resizing the preview window. For example if you resize the sidebar.

**Comment by azagaya** [comment]
Yes, this is because i didn't implement world coordinates. Everything is rendered relative to the widget, because it was easier to properly get coordinates when clicking on a texture. This should take some time to fix.

**Comment by Lodugh** [comment]
Well, you can give it low priority I think.

**Comment by azagaya** [comment]
hey! After some rewrite of the rendering, i got this working. Is this what you expected?

![relative](https://user-images.githubusercontent.com/46932830/79080759-09ff2c00-7cee-11ea-9460-f8728bf6866f.gif)

**Comment by azagaya** [comment]
I think this is fixed with the new world position. Im closing this, feel free to open if something is missing!
