### ISSUE TITLE
[Feature Request] values besides sliders

### ISSUE THREAD

**Issue by Lodugh** [azagaya/laigter#25]
I think it would be nice to have values besides the sliders because it helps to remember which value worked nicely. It'd also be useful to configure the light height exactly like in the engine you are using. It could also just be a switchable feature.

**Comment by azagaya** [comment]
Would be very useful indeed.

**Comment by azagaya** [comment]
Do you think it would be better to have a spinbox, so you can set the value there too, or just a label?

**Comment by Lodugh** [comment]
Just a label I would say.

**Comment by azagaya** [comment]
hey, what do you think of this? 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/46932830/70552033-617e6700-1b57-11ea-876e-7764ae0be367.gif)

**Comment by azagaya** [comment]
Or this two, in which i was able to solve the mouse offset:
![imagen](https://user-images.githubusercontent.com/46932830/70553906-d1dab780-1b5a-11ea-952e-d8608047394b.png)
![imagen](https://user-images.githubusercontent.com/46932830/70553918-d7d09880-1b5a-11ea-9703-b0a978ab7b18.png)

**Comment by dariuspranskus** [comment]
You guys reading my mind :) This would be very useful. And both label and value please. Thank you.

**Comment by azagaya** [comment]
@dariuspranskus so, like the examples above you think is right? you have the value inside the slider, and you can click on it and write a number to modify it more precisely.

**Comment by azagaya** [comment]
Or this: 
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/46932830/70637796-9bfb0900-1c16-11ea-9f45-56810ea7b9bb.gif)

**Comment by azagaya** [comment]
All previous have some problems when slider range is too high... i will have to think other solution

**Comment by azagaya** [comment]
Another option:
![imagen](https://user-images.githubusercontent.com/46932830/71116941-e4d13580-21b3-11ea-9b79-12adb9359f32.png)

**Comment by dariuspranskus** [comment]
I think this is ok. Another useful feature would be to save the settings as preset.

**Comment by azagaya** [comment]
@dariuspranskus preset saving and loading is already implemented! see comments in here #29 to see how they are used

**Comment by azagaya** [comment]
And this? 
![ezgif com-video-to-gif(7)](https://user-images.githubusercontent.com/46932830/71130079-d2fd8b80-21cf-11ea-9172-ab601ac6cf91.gif)

**Comment by azagaya** [comment]
I'm closing this due to the new sliders style.
