### ISSUE TITLE
Exporting preview non-crop issue

### ISSUE THREAD

**Issue by pixelinkmedia** [azagaya/laigter#27]
When i export just a preview image it exports the entire screen leaving the little image in the middle. Meaning I have to crop it to use it.  See the image below . Even though you can't see the boundary it extends three times wider and taller than the little 3D image itself . Save the image to your hard drive and then look at it you will see what I mean .

![3dtext](https://user-images.githubusercontent.com/51757955/68998365-53eaff80-087f-11ea-8ac1-a0966dbd00c4.png)

**Comment by azagaya** [comment]
Thanks for reporting this,ill try to fix this as soon as i can

**Comment by azagaya** [comment]
Hey, would you also check if there is a unchecked preview option in the export dock widget? That could be useful for you until the fix

**Comment by azagaya** [comment]
Now that i thought this for a while, perhaps the current behaviour of the tool button is fine. Because now you can export each individual preview in the preview dock widget, so this tool button can be used for exporting the whole canvas. What do you think?

**Comment by pixelinkmedia** [comment]
Thanks for asking my opinion. As a programmer myself....
The only use I would see for the entire canvas is if someone wanted to export the canvas so they can import it into a project, whether video or drawing program at the same canvas size as their projects canvas. This way they can keep the texture centered in the canvas . However, for this to be ideal use of that export canvas, a user would want to be able to set the width and height of their canvas, which they can't do right now.

Other than that I don't see where someone would need entire canvas.

Also, as a programmer, I would change the image you are using from was traditionally known as a video icon with the arrow, to some other icon representing exporting a campus. With the current icon my impression is that you can export the image as an animation or video only because of the play button arrow. That's just my concept from a programmer standpoint.

Also, I will be posting a feature suggestion on your itch page shortly concerning adding lights to the 
canvas and feature to save a project file so a user can save all their settings and come back to it later for the same image.

**Comment by azagaya** [comment]
Thanks for this suggestions! The only use case i would see to exporting the whole preview as is, it would be for presenting a mockup with many textures. As now you can handle multiple textures, may be the person in charge of the art wants to present how all the textures would look together.

About the feature suggestion, i would rather that you post them as issues here on github, because itch sometimes fails to send me an email with messages.

You are right about the icon, i will look for something better.

Thanks!

**Comment by azagaya** [comment]
Done
