### ISSUE TITLE
Use QtAwesome to replace hand drawn icons.

### ISSUE THREAD

**Issue by azagaya** [azagaya/laigter#35]
See: https://github.com/gamecreature/QtAwesome
It seems simple, and make apps look more professional imho.

**Comment by creepertron95** [comment]
@azagaya I was wondering, Is QtAwesome still being considered?

**Comment by azagaya** [comment]
I dont think so. The icons looks right now, and is not difficult to change colors. I prefer custom icons as you designed, and also, some icons like the add light one wouldnt have a similar one in Qt Awesome. Using QtAwesome would mean also we need another third party dependency. Ill close this, thanks for reminding me!
