### ISSUE TITLE
Update icons to be lighter when using a dark theme.

### ISSUE THREAD

**Issue by YeldhamDev** [azagaya/laigter#38]
Currently, all icons are still dark even if your OS' Qt theme is dark:
![Screenshot_20200305_091003](https://user-images.githubusercontent.com/30739239/75980381-41eaa680-5eda-11ea-948b-0656b2eeeda5.png)

**Comment by azagaya** [comment]
Hi! Thanks for the report! Yes, i'm working in a theme support for this. Maybe something like this:
![darktheme](https://user-images.githubusercontent.com/46932830/75980672-ba913900-5ec1-11ea-9dd7-1702bf37dc4c.gif)

Also, if i or any contributor manage to use QtAwesome, perhaps changing icons colors could be easier. Related to #35

**Comment by creepertron95** [comment]
@azagaya Do you think this problem is solved now with the new version?

**Comment by azagaya** [comment]
@creepertron95 Yes its solved i think, thanks for the reminder. The only think we need to take into account is making the new colors when creating a new theme.
