### ISSUE TITLE
Weird Behaviour (See Screencast)

### ISSUE THREAD

**Issue by flamendless** [azagaya/laigter#56]
See the attached zip file, it contains a video recording of the issue (sorry, i have no microphone)

Details:
1. Launching the app displays the window but with no content, you must first "click" inside or "move to another container (i3wm)" for the contents to finally show.
2. In order to see the changes when selecting widget, there must be first a "click" (not necessarily in the main window).
3. Sliders are working (you can see the real-time effect as the value gets updated)
4. Selecting on a tab like "Export" and "Texture", you must first make the "trigger click" for the widgets to get updated.

[laigter.zip](https://github.com/azagaya/laigter/files/4574609/laigter.zip)

System Information:
OS: ManjaroLinux x86_64 
Kernel: Linux 5.5.16-1-MANJARO 
WM: i3

**Comment by azagaya** [comment]
Could never reproduce this, sorry.
I think is related to #98 so ill close this older task
