### ISSUE TITLE
Preview export seemingly not working properly

### ISSUE THREAD

**Issue by Solstice245** [azagaya/laigter#59]
I am trying to export the files for some images. Other maps come out fine, but the preview export outputs an unusable image.

Example:
  [Source Image](https://i.imgur.com/Ej1QO8z.png)
  [Specular Output](https://i.imgur.com/4Vc3Q3I.png)
  [Preview Output](https://i.imgur.com/DTFRecz.png)

**Comment by azagaya** [comment]
Hi! Thanks for reporting the issue. I'm sorry for the trouble caused. I'll look at it as soon as i can.

**Comment by Solstice245** [comment]
[LaighterProject.zip](https://github.com/azagaya/laigter/files/4786324/LaighterProject.zip)

Here is the full project file if it helps any.

**Comment by azagaya** [comment]
@Solstice245 would you tell me which version of Laigter are you using and if you are trying to export with the toolbar button or the button in the export dock?

**Comment by Solstice245** [comment]
The version is 1.9.2. I exported with the button on the bottom right.

**Comment by azagaya** [comment]
Yeah, it seems to be a bug with animation. I seems to works fine with single images. I'll try too look at this soon.

**Comment by azagaya** [comment]
It also seems that if you have multiple textures, it just exports the preview of the first. 
You could work arround this for now this way.
1- Save the settings you are using
2- Open one frame, and export the preview
3- Open the other frame, remove the previous frame, and export again.
I'll try to fix this soon.

**Comment by Solstice245** [comment]
On my end it's behavior does not change even when I have just one image in the project. I'll add that the project crashes when I attempt to reopen it. Oh well, I guess for now I should try using a more stable version.

**Comment by azagaya** [comment]
Well, i'm not able to reproduce that behaviour.. Ill have to look deeper on it. Meanwhile, i exported the previews with your textures with the workarround i told you.
![PlatformCliffTile1Test_v](https://user-images.githubusercontent.com/46932830/84773052-39623b80-afb2-11ea-8171-862cd9771321.png)
![PlatformCliffTile2Test_v](https://user-images.githubusercontent.com/46932830/84773057-3b2bff00-afb2-11ea-8aad-ae839f9cfe9a.png)
I'll let you know when i fix this! Sorry

**Comment by azagaya** [comment]
Well, i fixed the problem with opening the project i think.

**Comment by azagaya** [comment]
fixed [here]( https://github.com/azagaya/laigter/commit/4608bb9b31fc5ddb9fc68141d04564899470c824)
Thanks for reporting!
