### ISSUE TITLE
Presets aren't exported on Windows 1.9.2

### ISSUE THREAD

**Issue by ffyhlkain** [azagaya/laigter#61]
The preset manager doesn't export the preset file into the specified folder. The files are still created in the apps data folder (<user>/Roaming/Laigter/Presets)

![export](https://user-images.githubusercontent.com/2485174/85853122-451fe000-b7b2-11ea-8331-d6691a2e2e1e.gif)

**Comment by ffyhlkain** [comment]
Seems like a permission issue. If I start the app with administration permission, it works fine. An error warning would be nice though if the file can't be saved.

**Comment by ffyhlkain** [comment]
Ok, found out that I was exporting into the Laigter folder (which needs admin permission as it is located in the Programs folder). Works fine when exporting into other folders (like my project folder). Still an error message popup would be great when exporting wasn't successful.

**Comment by azagaya** [comment]
I'll have to add a message about permission issues. Thanks for reporting!

**Comment by azagaya** [comment]
Hi! added the messages here 7a3db5d4a9ce1c48007a1d01243d0c21aa4b0d2f.
Closing this for now!
Thanks for reporting!
