### ISSUE TITLE
Suggestion for a new application icon

### ISSUE THREAD

**Issue by creepertron95** [azagaya/laigter#63]
Hi, I wanted to suggest a new application icon for Laigter.

Here is the icon I created:
![laigter256](https://user-images.githubusercontent.com/53346722/87214054-45aa9180-c2ef-11ea-994e-2df9adebe4ad.png)

SVG file at the bottom of issue

---
[laigter.tar.gz](https://github.com/azagaya/laigter/files/4906125/laigter.tar.gz)

**Comment by azagaya** [comment]
Hi! thanks a lot for the suggestion, your icon is much better than the current one! I would be very happy to use it for Laigter. So, i assume you are letting me use it freely, with no restrictions license or whatever right?
And could you share me also another one without the shadow? for using as light icon inside the app.

**Comment by creepertron95** [comment]
The icon is free for you to use. I have attached an archive that contains svgs of the no shadow version and a symbolic version of the icon.

![laigters](https://user-images.githubusercontent.com/53346722/87215509-c4f29200-c2fc-11ea-8f2e-c0675d640476.png)

---
[laigter-extrasvgs.tar.gz](https://github.com/azagaya/laigter/files/4906215/laigter-extrasvgs.tar.gz)

**Comment by azagaya** [comment]
Thanks a lot! Ill change them today. How would you like to be named in credits?

**Comment by azagaya** [comment]
What do you think? 
![image](https://user-images.githubusercontent.com/46932830/87225126-2b110080-c361-11ea-8c9f-9da3bc8a1e5a.png)

**Comment by creepertron95** [comment]
I think I will go by the name: creepertron95. The flame icons look awesome.

As aside: Perhaps the add light/flame icon should be updated as well?

**Comment by azagaya** [comment]
Yeah, i should change the add light icon also. Thanks for mentioning. I can add the SVG source in the repo, sure. In the app, ill use the pngs, but it would be useful to have the svg there too.

**Comment by azagaya** [comment]
I changed the icons, added you to contributors info tab, in this commit d44b451
Should we already close this as solved?
Thanks a lot!

**Comment by creepertron95** [comment]
Maybe I can improve the itch.io banner and thumbnail as well.

**Comment by azagaya** [comment]
That would be great! Yeah i used ubuntu font, with some borders. But is not needed to stick with that font. If you make the banner, would you leave some space for the megagrant logo there please?

**Comment by creepertron95** [comment]
Do you have the original image of the logo text? I will make sure the megagrant logo is there as well.

**Comment by azagaya** [comment]
Yes, i have all the original alternatives to the logo they sent me. I dont know if im allowed to share them by epics. I assume there should be no problem? Anyways its added to the readme so anyone can download it i guess. When i get back to the computer ill send you the image.

**Comment by creepertron95** [comment]
Oh, I meant the original Laigter logo.

**Comment by azagaya** [comment]
No, sadly i lost the original file on my old computer. I didn't save it to the repo. The only thing i have is the exported png. 
![image](https://user-images.githubusercontent.com/46932830/87228191-de83f000-c375-11ea-8b90-5e1139079ec6.png)

**Comment by creepertron95** [comment]
What do you think of this new logo?
![laigter-logo-preview](https://user-images.githubusercontent.com/53346722/87228264-bb514480-c365-11ea-913d-c2a11f1439b1.png)

**Comment by azagaya** [comment]
yeah its great!

**Comment by creepertron95** [comment]
I will post the logos and images shortly.

**Comment by azagaya** [comment]
Thanks a lot! i really appreciate your help.

**Comment by creepertron95** [comment]
Here are the logos:

![laigter-logo](https://user-images.githubusercontent.com/53346722/87228767-ebe6ad80-c368-11ea-8b45-af9b279c3af9.png)
![laigter-logo-black](https://user-images.githubusercontent.com/53346722/87228768-f0ab6180-c368-11ea-80bd-464c0943f9a3.png)
![laigter-logo-white](https://user-images.githubusercontent.com/53346722/87228775-f6a14280-c368-11ea-930e-d5e528b4bdf8.png)

And the itch.io banner and thumbnails
![laigter-thumnail](https://user-images.githubusercontent.com/53346722/87228814-44b64600-c369-11ea-8187-126985cfdaa4.png)
![laigter-new-banner](https://user-images.githubusercontent.com/53346722/87228817-50a20800-c369-11ea-90fc-78d220d03482.png)

Source SVGs and XCF files all in the archive below.

---

[laigter-presskit.tar.gz](https://github.com/azagaya/laigter/files/4907150/laigter-presskit.tar.gz)

**Comment by azagaya** [comment]
Wow thanks a lot! I may use the logos for a splash screen to be added soon. Ill use the banner for both itchio and the readme here on github. The thumbnail is going to appear in the browsers tab right?

**Comment by creepertron95** [comment]
The thumbnail is for the itch io thumbnail that is currently there.
![laigter-thumpreview](https://user-images.githubusercontent.com/53346722/87229000-56e4b400-c36a-11ea-8b05-4f1475bf9462.png)

**Comment by azagaya** [comment]
Yeah, i know. But it also appears in the browser tab right?
![image](https://user-images.githubusercontent.com/46932830/87229044-63253d00-c37b-11ea-8e25-da6ac0e7e173.png)
I already added the banner and thumbnail
Thanks a lot! I will probably use the same thumbnail, but changing the icon for a brush, for laigter's plugins page.

**Comment by creepertron95** [comment]
I think you can use the application icon for the browser tab. Try using the application icon as a favicon for the browser tab.

**Comment by azagaya** [comment]
Yeah, i discovered it right now. Thanks!

**Comment by creepertron95** [comment]
And I think that should be all of it.

**Comment by azagaya** [comment]
Yeah, i use gimp a bit every now and then. I used to do flyers for my band with it in the past.
What font did you use for the laigter logo?

**Comment by creepertron95** [comment]
Oh, I created it myself using Inkscape.

**Comment by azagaya** [comment]
Ah ok, i just planned to add put something like "Laigter's Plugins" or something. That can wain anyways, or i can make something myself. 
Thanks a lot again! I'm going to include the press kit in the repo, and close this by know. What do you think?

**Comment by creepertron95** [comment]
Sure, include the press kit and the issue should be complete.

**Comment by azagaya** [comment]
Thanks a lot!

**Comment by creepertron95** [comment]
@azagaya What do you think of these icons I designed for Laigter?

![newlight](https://user-images.githubusercontent.com/53346722/87970973-39aa9680-ca8a-11ea-8957-bc2d90a2a011.png)

**Comment by azagaya** [comment]
@creepertron95 they are really nice! I would definitely use them! are them svgs?

**Comment by creepertron95** [comment]
Yes, I just need to make them separate and upload them as svgs. I will post the archive when I am done.

**Comment by azagaya** [comment]
great thanks! In the gui i use png, but having them in svg would be nice in order to being able to export in different colors for different themes. I havent found a way to change color dinamycally though.

**Comment by creepertron95** [comment]
I made an archive of the icons in svg format. 

The icons are designed to be 24x24.

The small animation dock buttons (close and undock) are designed to be 10x10.

I also made a filetype icon for Laigter projects.

[laigter-icons.tar.gz](https://github.com/azagaya/laigter/files/4949524/laigter-icons.tar.gz)

**Comment by azagaya** [comment]
Cool thanks a lot! I'll add them as soon as i have some time.

**Comment by azagaya** [comment]
Apparently, i can just use svg as icon.

**Comment by azagaya** [comment]
@creepertron95 hey! would you make also an "export preview" icon please?
Thanks in advance

**Comment by creepertron95** [comment]
@azagaya I will go ahead and start making those icons.

**Comment by azagaya** [comment]
Thanks a lot!

**Comment by creepertron95** [comment]
How's the implementation coming so far?

**Comment by creepertron95** [comment]
@azagaya I created the icons for Delete and Export Preview.

![laigter-extra-icons](https://user-images.githubusercontent.com/53346722/88215713-b328bd00-cc21-11ea-8b6d-6f3e41919de6.png)

[extra-laigter-icon.tar.gz](https://github.com/azagaya/laigter/files/4961904/extra-laigter-icon.tar.gz)

**Comment by azagaya** [comment]
Great! thanks!

**Comment by creepertron95** [comment]
@azagaya I decided to create a few more icons in case. A Laigter and a default plugin symbol.

![few-more](https://user-images.githubusercontent.com/53346722/88216402-a789c600-cc22-11ea-8b4b-7c21175daee6.png)

[a-few-more.tar.gz](https://github.com/azagaya/laigter/files/4961938/a-few-more.tar.gz)

**Comment by azagaya** [comment]
Thanks! Im trying to use the theme system in Laigter, in order to be able to select icon based on the selected theme. There are no themes right now, but for future releases there will be.

**Comment by creepertron95** [comment]
Since the icons for the interface are getting overhauled and theme system implemented. Should the brush plugin icons be redesigned as well?

![brush-plugins](https://user-images.githubusercontent.com/53346722/88241946-4c22fc80-cc51-11ea-88a0-a8628b2764d5.PNG)

**Comment by azagaya** [comment]
yeah that should be needed too! also, some icon for the theme selector button would be nice

**Comment by creepertron95** [comment]
@azagaya I created an archive for those icons. Added icons for all 3 brush plugins. Added a theme selector icon and a settings icon. I also added a brush-template icon as a template for making icons for brush plugins.

peakBrush and roundBrush icons are designed to be 32x16.

![laigter-brush-icon](https://user-images.githubusercontent.com/53346722/88286889-17499080-ccb7-11ea-991a-f3c0bd5e9b28.png)

[laigter-brush-icons.tar.gz](https://github.com/azagaya/laigter/files/4965867/laigter-brush-icons.tar.gz)

**Comment by azagaya** [comment]
Great thanks a lot!
Ill add them today.

**Comment by creepertron95** [comment]
@azagaya Could I see a screenshot of the program after the icons are implemented to see what they look like in the GUI.

**Comment by azagaya** [comment]
sure! 
![imagen](https://user-images.githubusercontent.com/46932830/88304527-c352a200-ccde-11ea-8e42-bd6187dc02b0.png)
![imagen](https://user-images.githubusercontent.com/46932830/88304590-dd8c8000-ccde-11ea-93a0-489ebe9ee1f5.png)
Dark theme is WIP

**Comment by creepertron95** [comment]
@azagaya I see the plugin icons are a bit blurry. Have you scaled them to 24x24px?

**Comment by azagaya** [comment]
Yeah, i exported them in 48x48, and scaled to 24x24 in the gui. I undesrtood that was what you recommended.

**Comment by creepertron95** [comment]
@azagaya The other icons are fine. I was talking about these icons. They are still 20x20 in the gui.

![no24](https://user-images.githubusercontent.com/53346722/88311108-1b38db00-ccd6-11ea-9641-1a75583b519f.png)

**Comment by azagaya** [comment]
But you can check them here https://github.com/azagaya/laigter/blob/master/icons/Classic%20Laigter/custom-icons/plugin-delete.png
They were exported as 48x48, and set to 24x24 while loaded in the gui. IDK what could be wrong.

**Comment by azagaya** [comment]
Ok
i found it.. I was setting the wrong toolbar icon size. Sorry

**Comment by azagaya** [comment]
![imagen](https://user-images.githubusercontent.com/46932830/88316378-239d1000-ccee-11ea-8854-e8ee3f913c1a.png)
here it is @creepertron95 !

**Comment by azagaya** [comment]
@creepertron95 release with new icons is now out! you can get it on itch
