### ISSUE TITLE
On MAC laigter freezes when trying to select something in Visualization/View Mode drop down

### ISSUE THREAD

**Issue by dariuspranskus** [azagaya/laigter#64]
I am on MAC (currently on Big Sur beta, not sure if this is the case here), but when I try to select a different view mode, the drop down doesn't open and laigter freezes.

![image](https://user-images.githubusercontent.com/15170614/87258132-aea72a80-c4e4-11ea-9620-7fe153d177b7.png)

**Comment by azagaya** [comment]
Oh, thats strange. Let me try to reproduce it and ill get back to you.

**Comment by azagaya** [comment]
Hi!
I tested on Mojave, and could not reproduce this problem. If somehow i can get more info, i would be able to try it out. For now, i only can wait a contributor with your OSX version can compile laigter and try to debug it.

**Comment by webocs** [comment]
Can't reproduce it in mojave, any clues other than the OS version? Can you run the app from the terminal and see the output?

**Comment by dariuspranskus** [comment]
Tried to compile with Qt on Big Sur, and it works fine, probably this is some Big Sur incompatibility with the release build.

**Comment by dariuspranskus** [comment]
Closing, for the compiled app works fine on Big Sur.
