### ISSUE TITLE
Export transparent pixels as transparent in the normal map (premultiply alpha)

### ISSUE THREAD

**Issue by dariuspranskus** [azagaya/laigter#65]
Hi

Not sure if there is such a feature in laigter, but I would use one if available. I need this, because I want to pack all my normal maps into an atlas, and I strip all transparent pixels to fit all my sprites into one 2048x2048 page. Then I deal with the striped sprites in my app.

is it available, if not may I request an option in export to premultiply alpha onto exported normal maps?

Thank you.

**Comment by azagaya** [comment]
Hi! Currently there is no such option as tradicionally normal maps are just rgb images. But i could add it for next version. It was requested once in the past too. You mean, using the same transparent pixels as in the original image right?

**Comment by dariuspranskus** [comment]
@azagaya Yes, correct. Thank you. Appreciate that.

**Comment by azagaya** [comment]
Would it be better to have that option per each image or global? It wouold be easier to add per image i think, but would it make it more flexible or just more difficult to use?

**Comment by dariuspranskus** [comment]
One of the possible ways would be as follows. Currently, normal map settings (in the pane on the left) are applied to the selected images. Could we have a check box there, and apply it to the selected images as well? We can name it something like "Preserve alpha". Setting this option would cause the preview to show the transparent pixels and then cause images to be exported with transparent pixels applied to the normal map.

**Comment by azagaya** [comment]
Hi, yeah, i already did that before your response :)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/46932830/87343122-c00f2780-c522-11ea-9f90-0efd72545d1e.gif)
Ill push it today

**Comment by dariuspranskus** [comment]
@azagaya Amazing. Thanks

**Comment by dariuspranskus** [comment]
@azagaya When this will be available?

**Comment by azagaya** [comment]
@dariuspranskus i just pushed it. you can try it compiling the master branch. If it works for you, i can close this.

**Comment by dariuspranskus** [comment]
@azagaya Looks good to me. Good work. Thank you. Closing it now.
