### ISSUE TITLE
Changing settings stops working after going into "Preview"

### ISSUE THREAD

**Issue by cassiussa** [azagaya/laigter#66]
In version 1.10 on OSX, as soon as you go into the Preview mode you can no longer change any of the settings.  Updating the values does nothing.  If, however, you go into the Presets panel after and simply click Apply, you're then able to again change the settings and have them applied until the next time you go into Preview.

**Comment by azagaya** [comment]
Hi! What version of OSX? We tried yesterday and worked ok. Maybe platform independent problem?

**Comment by cassiussa** [comment]
This is on Catalina.  10.15.3 (19D76) specifically.  I haven't tried compiling from source as unfortunately I don't have the tools available to me.  But I can give it a go on latest build if there's an osx binary build?

**Comment by azagaya** [comment]
Now we have to fix this..

**Comment by cassiussa** [comment]
Further to this, I also notice the issue only occurs when, within Preview, I move the light.  If I do not move the light and go back to Normal Map, for example, I can continue to adjust the settings and see the result.  If in Preview I move the light, when going back to Normal Map (or any other) _then_ changing the settings doesn't result in any change to the image.

**Comment by azagaya** [comment]
probably a dumb question, but do you click again the texture before attemtping to change settings right?

**Comment by cassiussa** [comment]
Am I supposed to click the texture again?  I haven't been, no.  Just tried that now but the same results.

**Comment by cassiussa** [comment]
After doing that 3 times it did work. Let me see if I can find the pattern as to why my 3rd try was successful

**Comment by cassiussa** [comment]
ok this is probably going to sound crazy...

All the below are after visiting the Preview Mode.  And I only tested with Normal Map mode, not the others.

1. I can consistently get the changes to take effect with Normal Map, for example, if I not only click the image but move it.  From that point forward the settings work.  Verified this 5 times in a row.
2. I can only get changes to take effect randomly after clicking the image a number of times (sometimes twice, sometimes as many as 10 times)
3. Same as above but switching between clicking the image, updating the settings, clicking the image again.  <-- this one always takes more than 1 attempt, I never got it to work with just 1 try.

# 2 and 3 lead me to believe that in all my clicking I actually moved the image slightly without noticing (just like in #1).  That would also seem like why it was always a random number of clicks before it started working.

**Comment by azagaya** [comment]
Oh i see. Thats strange, but at least we got some leads. The need to clicl the texture comes from the fact that when you have multiple textures, you may want to change settings only to some of them, so you have to select.
For some reason, clicking is not enough in your system to select, you also have to move. Its like if the click event is not trigered until you move, idk why. Sorry for late response btw.. i was sleeping

**Comment by azagaya** [comment]
Its also possible that when fixing retina bug yesterday, scale and position end up in a wrong value, so some times its not considering you are clicking the texture.. would you try if clicking works in 1.10 from itch instead of int the current continuous release?

**Comment by cassiussa** [comment]
No need to apologize for the late reply, LOL.  I was also sleeping too. :)

I can confirm that in 1.10 a single click on the image allows for updating after, so it seems like the revisions to allow for zoom on OSX may have resulted in this issue.

**Comment by azagaya** [comment]
Im shooting in the dark right now, but would you try last continuous build?

**Comment by cassiussa** [comment]
Sorry for the delay.  Single dad of 3yr old and I'm at home through Covid ;)  So my attention is elsewhere.  LOL.  Anyways, yes, whatever changes you made appear to have fixed that up!

**Comment by azagaya** [comment]
No problem! thanks for helping me debug this! Ill close this then. If you notice anything else strange, please feel free to comment on this even if its closed, so i can reopen. I will also change the tittle of the issue to a better representation of what happened.
