### ISSUE TITLE
Need a button to disable anti aliasing

### ISSUE THREAD

**Issue by ironpowerkh** [azagaya/laigter#7]
![anti aliasing](https://user-images.githubusercontent.com/24843378/63511437-846e0800-c4e1-11e9-91e8-6547cefc5c27.png)

Very cool if they are a button to disable anti aliasing. Me i would like use it to make pixel art but it's difficult to see if it's good or not and make good change with anti alising. I think this update can interest lot of guys.

**Comment by azagaya** [comment]
Hi! have you tried the "pixelated" checkbox in the Visualization dock?
