### ISSUE TITLE
Custom Theme Support

### ISSUE THREAD

**Issue by maxtron95** [azagaya/laigter#70]
Hi, I was wanting to suggest custom themes now that the theme selector is implemented. I have a few suggestions.

1. Allow user to have custom window colors and custom icon themes. 

2. The dialog that appears after selecting the theme manager icon, That dialog is titled `Form`. I think should be labeled something like `Theme Manager`

3. I made a quick sketch of my ideas.
![lgtr-theme](https://user-images.githubusercontent.com/53346722/89429452-2e4ea080-d703-11ea-92f2-82be796278fa.png)

**Comment by azagaya** [comment]
Yes, i thought of something like that. The thing is now themes should be loaded as resources at compile time. I need to experiment on setting a directory, a template stylesheet file so user can easily change colors (even from a gui perhaps), and a function to programatically change colors of the svg icons to generate the corresponding ones. I made a bash script to help me to do the icon color changes, but it only works on linux. 
First of all, i will improve the theme selector as you suggested, and make a unique stylesheet template.
After that, and when i finish reworking tilemap support, i could work in the rest.

**Comment by azagaya** [comment]
Im sorry but i wont be able to work on this feature given my limited time...
