### ISSUE TITLE
Compile instructions do not work for Fedora Linux.

### ISSUE THREAD

**Issue by behelit2** [azagaya/laigter#75]
I went through the compile instructions and made sure all dependencies are installed. When I went to build, everything appears to build okay. However, when I go to run laigter.pro, I get this:
```
./laigter.pro: line 24: QT: command not found
./laigter.pro: line 26: TARGET: command not found
./laigter.pro: line 27: TEMPLATE: command not found
./laigter.pro: line 33: DEFINES: command not found
./laigter.pro: line 40: CONFIG: command not found
./laigter.pro: line 42: QMAKE_CXXFLAGS_RELEASE: command not found
./laigter.pro: line 44: SOURCES: command not found
./laigter.pro: line 67: HEADERS: command not found
./laigter.pro: line 93: FORMS: command not found
./laigter.pro: line 105: unix{: command not found
./laigter.pro: line 106: syntax error near unexpected token `PREFIX'
./laigter.pro: line 106: `    isEmpty(PREFIX) {'
```
How on earth would I fix this? I would really like to get this working in Linux, my entire workflow is there. It would be a royal PITA if I had to boot into Windows every time I wanted to use this app. 

I've never had this issue compiling C++ applications, but this is my first time using QT, so.

**Comment by Calinou** [comment]
`laigter.pro` is not an executable file. It's a Qt project file that can be used to generate a Makefile using `qmake-qt5|.

**Comment by behelit2** [comment]
Yeah... I tried using qmake-qt5 in the build directory, and like I said it built okay without any errors. But there is no obvious way to execute the freaking program. Do I need QtCreator for this method? 

PS: I tried one of the binaries and it seems to work fine.

**Comment by azagaya** [comment]
@behelit2 as @Calinou said, laigter.pro is just used to generate the makefile to compile the project after.
So first you run `qmake-qt5` in laigters directory, after that you run `make` and a binary called `laigter` with no extension should appear there... you should be able to run it.

**Comment by behelit2** [comment]
@azagaya Ah, that's the confusion. No laigter file appeared after the compile, but I didn't notice any errors while compiling... Weird. Anyway, the binary works fine. Thanks for the replies.

**Comment by azagaya** [comment]
I'll colse this then.

**Comment by behelit2** [comment]
Just to be clear, this issue isn't resolved... But I found an acceptable solution. I'm pretty sure it's not compiling correctly in Fedora on the command line.

**Comment by azagaya** [comment]
Ok.. ill reopen this.. but i thought @Calinou compiled fine on fedora.  Could you re do the compile steps and paste the output here please?

**Comment by behelit2** [comment]
Sure. 
[blah@localhost ~]$ sudo dnf install qt5-devel mesa-libGL-devel

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for blah: 
Last metadata expiration check: 2:16:21 ago on Thu Oct  1 07:39:52 2020.
Package qt5-devel-5.7.1-1.fc25.noarch is already installed, skipping.
Package mesa-libGL-devel-17.0.5-3.fc25.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
[blah@localhost ~]$ git clone https://github.com/azagaya/laigter
Cloning into 'laigter'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 3826 (delta 5), reused 8 (delta 3), pack-reused 3810
Receiving objects: 100% (3826/3826), 6.15 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2742/2742), done.
Checking connectivity... done.
[blah@localhost ~]$ cd laigter/
[blah@localhost laigter]$ mkdir build
[blah@localhost laigter]$ cd build/
[blah@localhost build]$ qmake-qt5 ../
Info: creating stash file /home/blah/laigter/build/.qmake.stash
Updating '/home/blah/laigter/translations/laigter_da.qm'...
Removing translations equal to source text in '/home/blah/laigter/translations/laigter_da.qm'...
    Generated 170 translation(s) (166 finished and 4 unfinished)
    Ignored 84 untranslated source text(s)
Updating '/home/blah/laigter/translations/laigter_en.qm'...
Removing translations equal to source text in '/home/blah/laigter/translations/laigter_en.qm'...
    Generated 182 translation(s) (182 finished and 0 unfinished)
    Ignored 73 untranslated source text(s)
Updating '/home/blah/laigter/translations/laigter_es.qm'...
Removing translations equal to source text in '/home/blah/laigter/translations/laigter_es.qm'...
    Generated 248 translation(s) (248 finished and 0 unfinished)
Updating '/home/blah/laigter/translations/laigter_fr.qm'...
Removing translations equal to source text in '/home/blah/laigter/translations/laigter_fr.qm'...
    Generated 177 translation(s) (173 finished and 4 unfinished)
    Ignored 64 untranslated source text(s)
Updating '/home/blah/laigter/translations/laigter_pt_BR.qm'...
Removing translations equal to source text in '/home/blah/laigter/translations/laigter_pt_BR.qm'...
    Generated 135 translation(s) (131 finished and 4 unfinished)
    Ignored 83 untranslated source text(s)
Updating '/home/blah/laigter/translations/laigter_ca_ES.qm'...
Removing translations equal to source text in '/home/blah/laigter/translations/laigter_ca_ES.qm'...
    Generated 125 translation(s) (121 finished and 4 unfinished)
    Ignored 84 untranslated source text(s)
Updating '/home/blah/laigter/translations/laigter_el.qm'...
Removing translations equal to source text in '/home/blah/laigter/translations/laigter_el.qm'...
    Generated 152 translation(s) (148 finished and 4 unfinished)
    Ignored 102 untranslated source text(s)
Updating '/home/blah/laigter/translations/laigter_tr.qm'...
Removing translations equal to source text in '/home/blah/laigter/translations/laigter_tr.qm'...
    Generated 200 translation(s) (196 finished and 4 unfinished)
    Ignored 54 untranslated source text(s)
Updating '/home/blah/laigter/translations/laigter_jp.qm'...
Removing translations equal to source text in '/home/blah/laigter/translations/laigter_jp.qm'...
    Generated 179 translation(s) (172 finished and 7 unfinished)
    Ignored 43 untranslated source text(s)
[blah@localhost build]$ make -j$(nproc)
Makefile:797: warning: overriding recipe for target 'moc_slider.cpp'
Makefile:767: warning: ignoring old recipe for target 'moc_slider.cpp'
/usr/lib64/qt5/bin/uic ../gui/about_dialog.ui -o ui_about_dialog.h
/usr/lib64/qt5/bin/uic ../gui/frame_splitter.ui -o ui_frame_splitter.h
/usr/lib64/qt5/bin/uic ../gui/language_selector.ui -o ui_language_selector.h
/usr/lib64/qt5/bin/uic ../gui/presets_manager.ui -o ui_presets_manager.h
/usr/lib64/qt5/bin/uic ../gui/remove_plugin_dialog.ui -o ui_remove_plugin_dialog.h
/usr/lib64/qt5/bin/uic ../gui/widgets/animation_dock.ui -o ui_animation_dock.h
/usr/lib64/qt5/bin/uic ../gui/widgets/sprite_properties_dock.ui -o ui_sprite_properties_dock.h
/usr/lib64/qt5/bin/uic ../gui/widgets/themeselector.ui -o ui_themeselector.h
/usr/lib64/qt5/bin/uic ../main_window.ui -o ui_main_window.h
/usr/lib64/qt5/bin/uic ../gui/nb_selector.ui -o ui_nb_selector.h
g++ -c -pipe -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../laigter -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o frame_splitter.o ../gui/frame_splitter.cpp
g++ -c -pipe -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../laigter -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o language_selector.o ../gui/language_selector.cpp
g++ -c -pipe -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../laigter -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o presets_manager.o ../gui/presets_manager.cpp
g++ -c -pipe -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../laigter -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o remove_plugin_dialog.o ../gui/remove_plugin_dialog.cpp
g++ -c -pipe -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../laigter -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o animation_dock.o ../gui/widgets/animation_dock.cpp
g++ -c -pipe -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../laigter -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o slider.o ../gui/widgets/slider.cpp
g++ -c -pipe -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../laigter -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o slider2.o ../gui/widgets/slider2.cpp
../gui/widgets/slider.cpp: In member function ‘void Slider::setValueToSpinBox(int)’:
../gui/widgets/slider.cpp:33:36: warning: unused parameter ‘v’ [-Wunused-parameter]
 void Slider::setValueToSpinBox(int v)
                                    ^
../gui/widgets/slider.cpp: In member function ‘virtual void Slider::mouseDoubleClickEvent(QMouseEvent*)’:
../gui/widgets/slider.cpp:86:51: warning: unused parameter ‘e’ [-Wunused-parameter]
 void Slider::mouseDoubleClickEvent( QMouseEvent * e ){
                                                   ^
../gui/widgets/slider2.cpp: In member function ‘void Slider2::setValueToSpinBox(int)’:
../gui/widgets/slider2.cpp:33:37: warning: unused parameter ‘v’ [-Wunused-parameter]
 void Slider2::setValueToSpinBox(int v)
                                     ^
g++ -c -pipe -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../laigter -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o sprite_properties_dock.o ../gui/widgets/sprite_properties_dock.cpp
g++ -c -pipe -O2 -O3 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../laigter -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o themeselector.o ../gui/widgets/themeselector.cpp
../gui/widgets/themeselector.cpp: In member function ‘void ThemeSelector::on_listWidget_itemClicked(QListWidgetItem*)’:
../gui/widgets/themeselector.cpp:30:3: error: ‘setFallbackSearchPaths’ is not a member of ‘QIcon’
   QIcon::setFallbackSearchPaths(QIcon::fallbackSearchPaths() << ":icons");
   ^~~~~
../gui/widgets/themeselector.cpp:30:33: error: ‘fallbackSearchPaths’ is not a member of ‘QIcon’
   QIcon::setFallbackSearchPaths(QIcon::fallbackSearchPaths() << ":icons");
                                 ^~~~~
Makefile:1000: recipe for target 'themeselector.o' failed
make: *** [themeselector.o] Error 1
make: *** Waiting for unfinished jobs....
[blah@localhost build]$
[blah@localhost build]$ cd ..
[blah@localhost laigter]$ ls
ACKNOWLEDGEMENTS  dist   icons.qrc   laigter.pro  main_window.cpp  README.md    src         thirdparty
build             gui    images      LICENSE      main_window.h    shaders      styles      translations
CONTRIBUTING.md   icons  images.qrc  main.cpp     main_window.ui   shaders.qrc  styles.qrc  translations.qrc

**Comment by azagaya** [comment]
There is an error with the icon themes.. could you check the version of qt with `qmake-qt5 --version`?

**Comment by behelit2** [comment]
Sure, it's:

```
qmake-qt5 --version
QMake version 3.0
Using Qt version 5.7.1 in /usr/lib64
```

**Comment by azagaya** [comment]
Oh, you need qt 5.14 at least.. what fedora version are you using? You should check if qt 5.14 is available in the repos.

**Comment by behelit2** [comment]
Ah, I was confused by the naming convention. I assumed 5.7.1 was higher than 5.14 at a glance. This can be closed, I tried with the updated libraries and it works fine.

**Comment by azagaya** [comment]
Im glad it worked! I'm closing it again then. 
Thanks for helping me test this.
