### ISSUE TITLE
Low contrast icons on dark OSX

### ISSUE THREAD

**Issue by dariuspranskus** [azagaya/laigter#82]
Hi 

Thanks again for the app.

Using laigter on dark BigSur the icons have low contrast [example here](https://imgur.com/a/IlASzO5)

Thank you

**Comment by Calinou** [comment]
See also #38.

Does this occur with other theme options in the app's preferences?

**Comment by azagaya** [comment]
Perhaps there is a way to check the OS theme and change the laigter's theme automatically?

**Comment by Calinou** [comment]
> Perhaps there is a way to check the OS theme and change the laigter's theme automatically?

It's possible that recent Qt versions expose this, but I'm not sure if this is available in 5.x or only in 6.0 onwards.

**Comment by azagaya** [comment]
@dariuspranskus does selecting a dark theme from the app itselfs solves this?

**Comment by azagaya** [comment]
I'll close this for now, as the theme in laigter should solve this. Feel free to write again if you still find issues.
