### ISSUE TITLE
Zoom out button just zoom in (idem with mouse wheel) Pop.Os! 20.10

### ISSUE THREAD

**Issue by pietrodito** [azagaya/laigter#85]
The zoom in and zoom out buttons produce the same result they both zoom in.

It is the same with the mouse wheel (with all my mouses).

**Comment by azagaya** [comment]
Oh, this is a regression. Are you using a hidpi display? Ill look at this soon

**Comment by azagaya** [comment]
I cannot reproduce this on Ubuntu 20.04. Could you confirm me if you are using high dpi display? And the version of Laigter please?

**Comment by azagaya** [comment]
Closing as i had no response
