### ISSUE TITLE
The View doesn't show anything

### ISSUE THREAD

**Issue by Arrow-x** [azagaya/laigter#87]
![Capture](https://user-images.githubusercontent.com/3308421/129592580-bacdec23-aa03-4061-96bf-33d0df324766.PNG)
v 1.10.6
I am on Windows with i3 3000 (OpenGL 3.1 support only is that the problem?)

**Comment by azagaya** [comment]
Hi,
Sorry for the late response, I was traveling.
It should work fine with OpenGL 3.1, although I didn't test with integrated intel GPUs. I'll try to test in other machines to see if I can reproduce it. In the meantime, would you try this things?

1. Run Laigter from the command line to see if any errors appear.
2. Try running laigter from the command line with -s parameter.
3. Try running in another machine, to see if this is specific to your hardware.

Thanks for reporting.

**Comment by Arrow-x** [comment]
No problem, I hope it was a safe trip, anyway 
1- No errors appear
2- Same result the program works but the view doesn't show anything, I can click around in it, and it will change selection, but nothing is shown
3- Tested on GTX 750 and an RX 460 and the programme works fine, bare in mind that this problem is on a mobile intel cpu, the i3 2330m

**Comment by Calinou** [comment]
As a workaround, you could use a software OpenGL implementation for Laigter only: https://github.com/pal1000/mesa-dist-win

**Comment by Arrow-x** [comment]
@Calinou strange I installed for Laigter and no change whatsoever

**Comment by Arrow-x** [comment]
switched to linux and the view is working fine

**Comment by azagaya** [comment]
@Arrow-x in that case it seems to be a problem with the drivers on Windows, as the dame hardware in Linux work. Maybe You could try updating the drivers in windows
