### ISSUE TITLE
you are not an engineer, never were, and never will be close.  Mechanical Engineering is the ONLY Engineering, period.

### ISSUE THREAD

**Issue by ghost** [azagaya/laigter#95]
@azagaya you are not an engineer, never were, and never will be close. There is no such this as "software" "engineer". That is the stupidest and most pathetic lie ever. Stop being disrespectful and insulting to Engineering and Engineers. You know nothing about what Engineering entails. Engineering means designing, building and producing real MECHANICAL systems, like turbojets and vehicular engines. It has nothing to do with sitting behind a keyboard and writing code or making software or games. Programming and software dev is easy and for young kids. Stop being a wannabe, Azagaya. Stop being childish and silly. Software dev is easy and for kids. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Software devs are ultra clowns and wannabes, who know nothing about engineering. They're just scummy liars who act like tryhards when they talk about a great subject like Engineering (Mechanical Engineering is the ONLY Engineering). Ya'll will never even come close to an engineer. So  making false claims against engineering, and quite being childish wannabes. And stop being disrespectful to real Engineers (Mechanical Engineering is the ONLY Engineering). 

Shame on you Azagaya for being stupid and trying to steal the word "Engineer" from real engineers (Mechanical Engineering is the ONLY ENGINEERING.). You ain't an engineer (and you'll never even come close).

Mechanical Engineering is the ONLY Engineering, period.

**Comment by jmc-figueira** [comment]
Sir, this is a Wendy's.

**Comment by azagaya** [comment]
Lol, I never Even claimed to be a Software engineer.
This is an old troll take btw.
