### ISSUE TITLE
Malware false positive report

### ISSUE THREAD

**Issue by wapcrazut** [azagaya/laigter#99]
Hi, first things first thanks for the excellent tool.

I scanned both the installable and portable versions, which were detected by at least one vendor in Virustotal.
- https://www.virustotal.com/gui/file/e5dec707fd3571c495caeeea37b2c37b4a8401ee841ffb7b2bac9db28a779df8/detection
- https://www.virustotal.com/gui/file/fbb86f990e2f20afed56729b71e1af4167a5053295ad3650df02a87b23ce1665/detection

Do we have an idea why? Is it possible to improve the source code or the compiling process not to trigger those false positives?

**Comment by Calinou** [comment]
> Do we have an idea why? Is it possible to improve the source code or the compiling process not to trigger those false positives?

Nothing can be done about it, other than reporting it as a false positive.

Alternatively, @azagaya could release Laigter on Steam and have people download it from Steam, so that the codesigning requirement is bypassed. This is *far* cheaper than buying an EV codesigning certificate (one-time $100 fee instead of $500+ per year).

**Comment by azagaya** [comment]
I should probably make it available through steam too yeah.

**Comment by wapcrazut** [comment]
> ...release Laigter on Steam and have people download it from Steam, so that the codesigning requirement is bypassed. This is _far_ cheaper than buying an EV codesigning certificate (one-time $100 fee instead of $500+ per year).

That's an interesting idea, if project donations are opened, contributors could help to pay the Steam fee.

**Comment by azagaya** [comment]
I usually receive voluntary tips through itch, as the price is set to "Pay what you want". I guess i should make something more specific and clear for this, like "rising 100u$d to put it on steam" as a goal.
Ill try to do so in a couple weeks, because right now I'm a bit short of time.

**Comment by Calinou** [comment]
Note that the Steam fee is refunded if you sell for $1,500 worth of copies on Steam.

**Comment by azagaya** [comment]
I guess i could do as Krita, and put a paid version of the binaries in the store. In that case I would put the 100u$d out of my pocket, and the users would have the benefit of easy updates.
But im not sure if Laigter users would be ok with that tbh.

**Comment by azagaya** [comment]
I wont be able to publish on steam anytime soon, so ill close this one for now and probably give it a second thought in the future.
